version: '3.4'
services:

  # nginx:
  #   image: nginx:latest
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./nginx/conf.d:/etc/nginx/conf.d:ro
  #   depends_on:
  #     - fastapi
  #   ports:
  #     - 80:80

  postgres:
    image: postgres:alpine
    volumes:
      - postgres_auth_data:/var/lib/postgresql/auth_data
    environment:
      POSTGRES_DB: ${AUTH_DB__NAME}
      POSTGRES_USER: ${AUTH_DB__USER}
      POSTGRES_PASSWORD: ${AUTH_DB__PASSWORD}
    env_file:
      - ./.env

  redis:
    image: redis:7.0.9-alpine

  flaskapp:
    build: flask_app
    restart: on-failure
    env_file:
      - ./.env
    depends_on:
      - postgres
      - redis


volumes:
  postgres_auth_data:
