version: '3.4'
services:

  # nginx:
  #   image: nginx:latest
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./nginx/conf.d:/etc/nginx/conf.d:ro
  #   depends_on:
  #     - fastapi
  #   ports:
  #     - 80:80

  postgres:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/schema:/docker-entrypoint-initdb.d
    env_file:
      - ./.env

  redis:
    image: redis:7.0.9-alpine

  flaskapp:
    build: flask_app
    restart: on-failure
    env_file:
      - ./.env
    depends_on:
      - postgres
      - redis


volumes:
  postgres_data:
  elasticsearch_data:
